### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by JimDude7404** [MWisBest/StadiEm#1]
Can you make a release thats already compiled

**Comment by Gabi10017** [comment]
https://drive.google.com/file/d/1_HXN-1yywvOYilD1EYVY8ByU4-SdJxn_/view?usp=sharing The build with the latest commits, compiled by me.

Prerequisites:
ViGEmBus
.NetCore App - for Desktop
.NetFramework 4.5
Requirement: Run the program using Run as Administrator for the best performance.

Optional: Use HidHide in order to avoid double commands.

**Comment by RexSonic** [comment]
https://github.com/RexSonic/StadiEm

**Comment by cillin89** [comment]
> https://github.com/RexSonic/StadiEm

Any chance of making a new release that's compatible with the new bluetooth mode?

**Comment by JimDude7404** [comment]
It already is, just run it and it works

**Comment by kastle1** [comment]
Hmmm, I'm also having problems with this release over bluetooth.  When connected over usb cable, everything works perfectly.  Disconnecting the usb, and connecting via bluetooth results in the StadiEm app crashing with the following error in the event viewer.  Any ideas on why it might be doing this on my PC?

Faulting application name: StadiEm.exe, version: 1.0.0.0, time stamp: 0x61731974
Faulting module name: KERNELBASE.dll, version: 10.0.18362.267, time stamp: 0xf09944f9
Exception code: 0xe0434352
Fault offset: 0x000000000003a839
Faulting process id: 0x1684
Faulting application start time: 0x01d92fa5fc624cc7
Faulting application path: C:\Program Files (x86)\stadiacontroller\StadiEm_RedSonic\StadiEm.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9396b11a-a860-400f-8b28-26dfd0f31c88
Faulting package full name: 
Faulting package-relative application ID:

**Comment by flechaig** [comment]
Same error here.
And another one just before with a hard coded path:
`Application: StadiEm.exe
CoreCLR Version: 4.700.22.55902
.NET Core Version: 3.1.32
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: Operation failed after some time.
 ---> System.ComponentModel.Win32Exception (87): The parameter is incorrect.
   --- End of inner exception stack trace ---
   at StadiEm.Device.Stadia.StadiaController.write_thread() in C:\Users\serha\Downloads\StadiEm\StadiEm\Device\Stadia\StadiaController.cs:line 147
   at StadiEm.Device.Stadia.StadiaController.<.ctor>b__11_1() in C:\Users\serha\Downloads\StadiEm\StadiEm\Device\Stadia\StadiaController.cs:line 81
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`

Also noticed that rumble doest not work at all when connected viia Bluetooth (seems to be due to the generic driver of Windows).
